<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title></title>

  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    p {
      font-family: arial, sans-serif;
    }

    td {
      border: 1px solid #000000;
      text-align: center;

    }

    th {
      border: 1px solid #000000;
      text-align: center;

    }

    .tr-p {
      font-family: arial, sans-serif;
      font-size: 15px;
    }

    .tr-pp {
      font-size: 14px;

    }
  </style>
</head>

<body>

  <img src="{{ public_path('assets/images/arctic-zone-logo.png') }}" 
  align="left" height="60" width="150">
  <p style="margin-left: 10rem;"><b>Service Requested Report</b> <br>
    <small>Generated By: Arctic Zone Thermo Solutions Inc.</small> <br>
    <small>
      Date and Time: {{ $date_from }} - {{ $date_to }} 
      {{ date('g:i A') }}
    </small></p>
  <hr>
  <table>
    <thead>
      <tr class="tr-p">
        <th><b>SRID</b></th>
        <th><b>Date</b></th>
        <th><b>Requestor</b></th>
        <th><b>Address</b></th>
        <th><b>Contact No.</b></th>
        <th><b>Work Done</b></th>
        <th><b>Amount</b></th>
      </tr>
    </thead>
    <tbody>
      @foreach ($service_requests as $service_request)
        <tr class="tr-pp">
          <td>{{ $service_request['id'] }}</td>
          <td>{{ date('F d y', strtotime($sr['service_date'])) }}</td>
          <td>{{ $service_request['client']['firstname'] . ' ' . $service_request['client']['lastname'] }}</td>
          <td>{{ $service_request['service_address'] }}</td>
          <td>{{ $service_request['client']['contact_number'] }}</td>
          <td>Cleaning Window (2) Non-inverter (1) Inverter (1) Samsung (1) Koppel (1)</td>
          <td>{{ number_format($service_request['total_amount'], 2) }}</td>
        </tr>
      @endforeach
      
    </tbody>
  </table>
</body>

</html>