<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title></title>

  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    p {
      font-family: arial, sans-serif;
    }

    td {
      border: 1px solid #000000;
      text-align: center;

    }

    th {
      border: 1px solid #000000;
      text-align: left;

    }

    .tr-p {
      font-family: arial, sans-serif;
      font-size: 15px;
    }

    .tr-pp {
      font-size: 14px;
    }
  </style>
</head>

<body>
  <img src="{{ public_path('assets/images/arctic-zone-logo.png') }}" 
  align="left" height="60" width="150">
  <p style="margin-left: 10rem;"><b>Service Request Status Report</b> <br>
    <small>Generated By: Arctic Zone Thermo Solutions Inc.</small><br>
    <small>
      Date and Time: {{ $date_from }} - {{ $date_to }} 
      {{ date('g:i A') }}
    </small></p>
  <hr>

  <table>
    <thead>
      <tr class="tr-p">
        <td><b>SRID</b></td>
        <td><b>Service</b></td>
        <td><b>Property</td>
        <td><b>Requested By</b></td>
        <td><b>Assigned By</b></td>
        <td><b>Date/Time</b></td>
        <td><b>Status</b></td>
      </tr>
    </thead>
    <tbody>
      @foreach ($service_requests as $sr)
      <tr class="tr-pp">
        <td>{{ $sr['id'] }}</td>
        <td>{{ $sr['service_type']['name'] }}</td>
        <td>{{ $sr['property']['name'] }}</td>
        <td>{{ $sr['client']['firstname'] . ' ' . $sr['client']['lastname'] }}</td>
        <td>
          @foreach ($sr['technicians'] as $tech)
              {{ $tech['tech_info']['firstname'] . ' ' . $tech['tech_info']['lastname'] }}
              <br>
          @endforeach
        </td>
        <td> {{ date('M d y', strtotime($sr['service_date'])) }} <br>
          {{ date('g:iA', strtotime($sr['timeslot']['start'])) }} - 
          {{ date('g:iA', strtotime($sr['timeslot']['end'])) }}
        </td>
        <td>
          {{ ucfirst($sr['status']) }}
        </td>
      </tr>
      @endforeach
      
    </tbody>

    <h5>TOTAL OPEN REQUESTS: {{ $status_group['new'] }} </h5>
    <h5>TOTAL PENDING REQUESTS: {{ $status_group['pending'] }} </h5>
    <h5>TOTAL COMPLETED REQUESTS: {{ $status_group['completed'] }} </h5>
    <h5>TOTAL ON GOING REQUESTS: {{ $status_group['on_going'] }}  </h5>
    <h5>TOTAL CANCELLED REQUESTS: {{ $status_group['cancelled'] }} </h5>

    <h5>TOTAL REQUESTS: {{ count($service_requests) }} </h5>


  </table>
</body>

</html>