<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title></title>

  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    p {
      font-family: arial, sans-serif;
    }

    td {
      border: 1px solid #000000;
      text-align: center;

    }

    th {
      border: 1px solid #000000;
      text-align: center;

    }

    .tr-p {
      font-family: arial, sans-serif;
      font-size: 15px;
    }

    .tr-pp {
      font-size: 14px;

    }
  </style>
</head>

<body>
  <img src="{{ public_path('assets/images/arctic-zone-logo.png') }}"  
  align="left" height="60" width="150">
  <p style="margin-left: 10rem;"><b>Technician Service Job Report</b> <br>
    <small>Generated By: Arctic Zone Thermo Solutions Inc.</small><br>
    <small>
      Date and Time: {{ $date_from }} - {{ $date_to }} 
      {{ date('g:i A') }}
    </small></p>
  <hr class="md-4">
  <p><b>Technician ID:</b> {{ $technician['id'] }}
    <br>
    <b>Technician Name:</b>
    {{ $technician['tech_info']['firstname'] . ' ' . $technician['tech_info']['lastname'] }} </p>

  <table>
    <thead>
      <tr class="tr-p">
        <th><b>SRID</b></th>
        <th><b>Service</b></th>
        <th><b>Client Name</b></th>
        <th><b>Date Start</b></th>
        <th><b>Date Finish</b></th>
        <th><b>Remarks</b></th>
        <th><b>Status</b></th>
      </tr>
    </thead>

    <tbody>
      @foreach ($technician['service_requests'] as $sr)
      <tr class="tr-pp">
        <td>{{ date('Y') . '-0000' . $sr['id'] }}</td>
        <td>
          @foreach ($sr['appliances'] as $appliance)
            {{ $appliance['service_type']['name'] . ' - ' . $appliance['name'] }} <br>
          @endforeach
        </td>
        <td>{{ $sr['client']['firstname'] . ' ' . $sr['client']['lastname'] }}</td>
        <td>{{ date('F d, Y', strtotime($sr['service_date'])) }}</td>
        <td>
          @if ($sr['status'] === 'completed')
          {{ date('F d, Y', strtotime($sr['completed_at'])) }}
          @endif
        </td>
        <td>
          @if ($sr['status'] === 'completed' && count($sr['remarks']) === 2)
            @if ($sr['remarks'][0]['technician_id'] === $technician['id'])
              {{ $sr['remarks'][0]['name'] }}
            @else
              {{ $sr['remarks'][1]['name'] }}
            @endif
          @endif
        </td>
        <td>{{ ucfirst($sr['status'])}} </td>
      </tr>
      @endforeach
    </tbody>



  </table>


</body>

</html>